#pragma once

#ifndef VALVE_INTERFACES
#define VALVE_INTERFACES

// client.dll
#define VCLIENTENTITYLIST_INTERFACE_VERSION "VClientEntityList003"

// engine.dll
#define VENGINE_CLIENT_INTERFACE_VERSION "VEngineClient014"
#define VMODELINFO_CLIENT_INTERFACE_VERSION	"VModelInfoClient006"
#define ENGINETRACE_CLIENT_INTERFACE_VERSION "EngineTraceClient004"

#endif
